name: Lint TS code

on:
  pull_request:
    branches: [ master ]

jobs:
  Lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install NPM deps
        run: npm ci

      - name: Lint TS Code according to gts
        run: npm run lint
