name: Run all AEG tests

on:
  pull_request:
    branches: [ master ]

jobs:
  AEG_Structure_Tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install NPM dependencies
        run: npm ci

      - name: Run all vitest tests
        run: npx vitest
