
name: Validate HTML and CSS

on:
  pull_request:
    branches: [ master ]

jobs:
  validateHTML:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        css: true
        root: src/

            
