name: Validate Documentation Build

on:
  pull_request:
    branches: [ master ]

jobs:
  buildDocs:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install NPM deps
        run: npm ci

      - name: Build Docs
        run: npm run build-docs
