name: Validate Build

on:
  pull_request:
    branches: [ master ]

jobs:
  Build_Ubuntu:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install NPM deps
        run: npm ci

      - name: use Vite to compile the application
        run: npm run build

  Build_Windows:
    timeout-minutes: 5
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install NPM deps
        run: npm ci

      - name: use Vite to compile the application
        run: npm run build
